events { worker_connections 1024; }
http {
    upstream search_servers {
        server recommender-app:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://search_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}